#!/bin/sh
set -e

failed=0
for test in $*
do
	echo Running test $test...
	if env - bash $test
	then
		echo 'Done.'
	else
		echo '******************************Failed!******************************'
		failed=$(( $failed + 1 ))
	fi
done 2>&1
echo "$# tests run, $failed failed"
exit $failed
