.TH mailq 1
.SH NAME
mailq \- List the contents of the
.B nullmailer
queue.
.SH SYNOPSIS
.B mailq
.SH DESCRIPTION
This program loads the contents of the
.B nullmailer
queue and presents a short summary of its contents.
.SH OPTIONS
None.
.SH RETURN VALUE
Exits 0 if it was successful, otherwise it prints a diagnostic message
to standard error and exits 1.
.SH SEE ALSO
nullmailer-queue(8),
sendmail(1)
