.TH nullmailer 7
.SH NAME
nullmailer \- Overview of nullmailer documentation
.SH INTRODUCTION
.B nullmailer
is a simple and secure relay-only mail transport agent.
.P
Documentation on how messages are reformatted and injected into the
queue can be found in
.BR nullmailer-inject (1).
Documentation on how messages are actually inserted into the queue can
be found in
.BR nullmailer-queue (8).
The process of sending queued messages is described in
.BR nullmailer-send (8).
.P
The following table lists all the control files used by
.BR nullmailer .
.P
.RS
.nf
.ta 5c
control file	used by
.I adminaddr	\fBnullmailer-dsn\fR, \fBnullmailer-queue
.I allmailfrom	\fBnullmailer-queue
.I defaultdomain	\fBnullmailer-dsn\fR, \fBnullmailer-inject
.I defaulthost	\fBnullmailer-dsn\fR, \fBnullmailer-inject
.I doublebounceto	\fBnullmailer-dsn
.I helohost	\fBnullmailer-send
.I idhost	\fBnullmailer-dsn\fR, \fBnullmailer-inject
.I maxpause	\fBnullmailer-send
.I me		\fBnullmailer-dsn\fR, \fBnullmailer-inject
.I pausetime	\fBnullmailer-send
.I remotes	\fBnullmailer-send
.I sendtimeout	\fBnullmailer-send
.fi
.RE
