#! /bin/sh
#
# nullmailer	Start/Stop the nullmailer-send daemon.
#
# chkconfig: 345 80 20
# description: nullmailer is the nullmailer mail transmission daemon
# processname: nullmailer-send
# config: /etc/nullmailer

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
case "$1" in
  start)
	svc-start nullmailer
	;;
  stop)
	svc-stop nullmailer
	;;
  status)
	svc-status nullmailer
	;;
  restart)
	$0 stop
	sleep 1
	$0 start
	;;
  reload)
	echo -n "Starting nullmailer reload cycle: "
  	svc -h $lock
	echo done
	;;
  *)
	echo "Usage: Xd {start|stop|status|restart|reload}"
	exit 1
esac

exit 0
